source 'https://rubygems.org'

gem 'byebug'
gem 'cucumber', '4.1.0'
gem 'httparty', '0.18.0'
gem 'rspec', '3.10.0'
gem 'faker', '2.13.0'
gem 'cpf_cnpj', '0.5.0'
gem 'cpf_generator'
gem 'parallel_tests'
gem 'allure-cucumber'
gem 'yaml'